/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#d0c5af",
        "on-tertiary": "#082b72",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-primary-container": "#554300",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#c5b393",
        "surface-container": "#201f1f",
        "on-primary-fixed-variant": "#574500",
        "secondary-container": "#52452c",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#52452c",
        "on-secondary": "#3a2f18",
        "outline": "#99907c",
        "on-tertiary-fixed-variant": "#27438a",
        "surface": "#131313",
        "secondary": "#d7c4a4",
        "muted-gold": "#79786C",
        "surface-container-highest": "#353534",
        "primary": "#f2ca50",
        "on-secondary-fixed": "#241a06",
        "inverse-surface": "#e5e2e1",
        "charcoal-surface": "#1A1A1A",
        "surface-bright": "#3a3939",
        "tertiary-fixed": "#dbe1ff",
        "off-white-text": "#F5F5F5",
        "on-tertiary-fixed": "#00174b",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#ffe088",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "glass-border": "rgba(229, 209, 176, 0.2)",
        "primary-container": "#d4af37",
        "primary-fixed-dim": "#e9c349",
        "secondary-fixed": "#f4e0be",
        "on-surface": "#e5e2e1",
        "error": "#ffb4ab",
        "outline-variant": "#4d4635",
        "surface-container-lowest": "#0e0e0e",
        "inverse-primary": "#735c00",
        "on-primary-fixed": "#241a00",
        "surface-tint": "#e9c349",
        "on-tertiary-container": "#254188",
        "tertiary-container": "#97b0ff",
        "background": "#131313",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#d7c4a4",
        "on-primary": "#3c2f00",
        "tertiary": "#bfcdff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "80px",
        "container-max": "1440px",
        "unit": "8px",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      fontFamily: {
        "interactive": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"]
      }
    },
  },
  plugins: [],
}
